### ISSUE TITLE
Not able to call dynamsoft.load in other functions.

### ISSUE THREAD

**Issue by Jess892007** [dynamsoft-dwt/dwt-angular-advanced#2]
IS there a way to create or call first instance of Dynamsoft.DWT.Load() in other methods or functions or events without calling it in ngInit() .

**Comment by Grace-Dynamsoft** [comment]
Dynamsoft.DWT.Load() can be called anytime if our source files are entirely loaded.
suggest adding a button to call Dynamsoft.DWT.Load() 

And another solution, you can adopt AutoLoad instead of manual load: 
set Dynamsoft.DWT.AutoLoad = true, which will make Loading happens automatically
